<?php
/** @var \Commerce365\CreditMemos\Block\CreditMemoList  $block */
$totalResults = 0;
$creditMemos = [];

$creditMemosResponse = $this->getCreditMemos();
if (!empty($creditMemosResponse)) {
    $creditMemos = $creditMemosResponse["salesDocuments"];
    $totalResults = $creditMemosResponse["totalResults"];
}
?>

<div class="table-wrapper orders-history">
<?php if (count($creditMemos) > 0): ?>
    <form action="<?= $this->getFilterActionUrl() ?>" method="get">
        <div class="search-form-fields">
            <input type="text" placeholder="<?= __('Search...') ?>" name="searchString"/>
            <button type="submit" title="<?= __('Search') ?>" class="action primary">
                <span><?= __('Search') ?></span>
            </button>
        </div>
    </form>
    <?php if ($this->getSearchString()): ?>
        <?= __('Current filter')?>: <?= $this->getSearchString()?>
        <a href="<?= $this->getFilterActionUrl()?>"><?= __('Reset') ?></a>
    <?php endif; ?>
    <table class="data table table-order-items history" id="my-orders-table">
        <thead>
        <tr>
            <th scope="col" class="col id">
                <a href="<?= $this->getSortLink('No.')?>">
                    <?= __('Credit Memo #') ?>
                    <?= $this->getSortIcon('No.') ?>
                </a>
            </th>
            <th scope="col" class="col date">
                <a href="<?= $this->getSortLink('Document Date')?>">
                    <?= __('Date') ?>
                    <?= $this->getSortIcon('Document Date') ?>
                </a>
            </th>
            <th scope="col" class="col shipping">
                <a href="<?= $this->getSortLink('Sell-to Customer Name')?>">
                    <?= __('Credit To') ?>
                    <?= $this->getSortIcon('Sell-to Customer Name') ?>
                </a>
            </th>
            <th scope="col" class="col total">
                <a href="<?= $this->getSortLink('Amount Including VAT')?>">
                    <?= __('Credit Total') ?>
                    <?= $this->getSortIcon('Amount Including VAT') ?>
                </a>
            </th>
            <th scope="col" class="col total">
                <a href="<?= $this->getSortLink('Remaining Amount')?>">
                    <?= __('Open Amount') ?>
                    <?= $this->getSortIcon('Remaining Amount') ?>
                </a>
            </th>
            <th scope="col" class="col actions">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($creditMemos as $creditMemo): ?>
            <tr>
                <td data-th="Order #" class="col id"><?= $creditMemo["No."] ?></td>
                <td data-th="Date" class="col date"><?= date_format(date_create($creditMemo["Document Date"]), "d-m-Y") ?></td>
                <td data-th="Ship To #" class="col id"><?= $creditMemo["Sell-to Customer Name"] ?></td>
                <td data-th="Total" class="col total"><?= $creditMemo["Currency Code"] ?> <?= number_format((float)$creditMemo["Amount Including VAT"], 2, ',', '.') ?></td>
                <td data-th="Total" class="col total"><?= $creditMemo["Currency Code"] ?> <?= number_format((float)$creditMemo["Remaining Amount"], 2, ',', '.') ?></td>
                <td data-th="Actions" class="col actions">
                    <a href="<?= $this->getViewUrl($creditMemo["id"]) ?>" class="action view">
                        <span><?= __("View Credit Memo") ?></span>
                    </a>
                    <a href="<?= $creditMemo["PDFUrl"] ?>" class="action order" target="_blank">
                        <span>PDF</span>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="message info empty"><span><?= __('No credit memos found.') ?></span></div>
<?php endif; ?>
</div>

<?php if ($totalResults > $block->getPageSize()): ?>
    <div>
        <?= __('Page:') ?> <?= $block->getPage() ?> <?= __('of') ?> <?= $creditMemosResponse["totalPages"] ?>
    </div>
    <div>
        <?php if ($block->getPage() > 1): ?>
        <a href="<?= $this->getPreviousPageLink($block->getPage()) ?>" class="action order"><?= __('Previous') ?></a>
        <?php endif; ?>
        <?php if ($block->getPage() > 1 && $block->getPage() < $creditMemosResponse["totalPages"]): ?>
            -
        <?php endif; ?>
        <?php if ($block->getPage() < $creditMemosResponse["totalPages"]): ?>
        <a href="<?= $this->getNextPageLink($block->getPage()) ?>" class="action order"><?= __('Next') ?></a>
        <?php endif; ?>
    </div>
<?php endif; ?>


<!--

Below is a list of all sales credit memo header fields
All these fields are available in the API response, as well as any custom field added by customer/partner/other ISV

[SelltoCustomerNo]
[No]
[BilltoCustomerNo]
[BilltoName]
[BilltoName2]
[BilltoAddress]
[BilltoAddress2]
[BilltoCity]
[BilltoContact]
[YourReference]
[ShiptoCode]
[ShiptoName]
[ShiptoName2]
[ShiptoAddress]
[ShiptoAddress2]
[ShiptoCity]
[ShiptoContact]
[PostingDate]
[ShipmentDate]
[PostingDescription]
[PaymentTermsCode]
[DueDate]
[PaymentDiscountPercentage]
[PmtDiscountDate]
[ShipmentMethodCode]
[LocationCode]
[ShortcutDimension1Code]
[ShortcutDimension2Code]
[CustomerPostingGroup]
[CurrencyCode]
[CurrencyFactor]
[CustomerPriceGroup]
[PricesIncludingVAT]
[InvoiceDiscCode]
[CustomerDiscGroup]
[LanguageCode]
[SalespersonCode]
[OnHold]
[Amount]
[AmountIncludingVAT]
[VATRegistrationNo]
[ReasonCode]
[GenBusPostingGroup]
[TransactionType]
[TransportMethod]
[VATCountryRegionCode]
[SelltoCustomerName]
[SelltoCustomerName2]
[SelltoAddress]
[SelltoAddress2]
[SelltoCity]
[SelltoContact]
[BilltoPostCode]
[BilltoCounty]
[BilltoCountryRegionCode]
[SelltoPostCode]
[SelltoCounty]
[SelltoCountryRegionCode]
[ShiptoPostCode]
[ShiptoCounty]
[ShiptoCountryRegionCode]
[Correction]
[DocumentDate]
[ExternalDocumentNo]
[PaymentMethodCode]
[TaxAreaCode]
[TaxLiable]
[VATBusPostingGroup]
[VATBaseDiscountPercentage]
[PrepaymentCreditMemo]
[PrepaymentOrderNo]
[Canceled]
[Paid]
[RemainingAmount]
[CustLedgerEntryNo]
[InvoiceDiscountAmount]
[CampaignNo]
[SelltoContactNo]
[BilltoContactNo]
[ResponsibilityCenter]
[ReturnOrderNo]
[AllowLineDisc]
[NoOfLines]
[PdfFileName]
[PdfUrl]

-->

<!--

Below is a list of all sales credit memo line fields

[SelltoCustomerNo]
[DocumentNo]
[LineNo]
[Type]
[No]
[NoIntegrationId]
[LocationCode]
[PostingGroup]
[ShipmentDate]
[Description]
[Description2]
[UnitofMeasure]
[Quantity]
[UnitPrice]
[UnitCostLCY]
[VATPercentage]
[LineDiscountPercentage]
[LineDiscountAmount]
[Amount]
[AmountIncludingVAT]
[AllowInvoiceDisc]
[GrossWeight]
[NetWeight]
[ShortcutDimension1Code]
[ShortcutDimension2Code]
[CustomerPriceGroup]
[BilltoCustomerNo]
[InvDiscountAmount]
[GenBusPostingGroup]
[GenProdPostingGroup]
[TransactionType]
[TransportMethod]
[VATBusPostingGroup]
[VATProdPostingGroup]
[VATBaseAmount]
[UnitCost]
[LineAmount]
[VATDifference]
[VATIdentifier]
[PrepaymentLine]
[PostingDate]
[VariantCode]
[BinCode]
[QtyperUnitofMeasure]
[UnitofMeasureCode]
[QuantityBase]
[ResponsibilityCenter]
[ItemCategoryCode]
[Nonstock]
[ProductGroupCode]
[ReturnReceiptNo]
[ReturnReceiptLineNo]
[ReturnReasonCode]
[AllowLineDisc]
[CustomerDiscGroup]

-->
