<?php
/** @var \Commerce365\CreditMemos\Block\CreditMemoDetails $block */
$creditMemo = $block->getCreditMemo();
$creditMemoLines = $creditMemo["Lines"];
$status = 'Credited';
if ((float)$creditMemo["Remaining Amount"] > 0) {
    $status = 'Open (remaining: &euro; ' . number_format((float)$creditMemo["Remaining Amount"], 2, ',', '.') . ')';
}

?>

<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper" >Credit Memo # <?php echo $creditMemo["No."]; ?> </span>
    </h1>
    <span class="order-status"><?php echo $status ?></span>
    <div class="order-date">
        <span class="label"><?php echo __('Credit Memo Date:') ?></span> <date><?php echo date_format(date_create($creditMemo["Document Date"]), "d-m-Y") ?></date>
    </div>
</div>

<div class="actions-toolbar order-actions-toolbar">
    <div class="actions">
        <a href="<?php echo $creditMemo["PDFUrl"] ?>" class="action order" target="_blank">
            <span><?php echo __('Download PDF') ?></span>
        </a>
    </div>
</div>

<ul class="items order-links"><li class="nav item current"><strong><?php echo __('Items Credited') ?></strong></li></ul><div class="order-details-items ordered">

    <div class="order-title">
        <strong><?php echo __('Items Credited') ?></strong>
    </div>

    <div class="table-wrapper order-items">
        <table class="data table table-order-items" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Items Credited') ?></caption>
            <thead>
            <tr>
                <th class="col name"><?php echo __('Product Name') ?></th>
                <th class="col sku"><?php echo __('SKU') ?></th>
                <th class="col price"><?php echo __('Price') ?></th>
                <th class="col qty"><?php echo __('Qty') ?></th>
                <th class="col subtotal"><?php echo __('Subtotal') ?></th>
            </tr>
            </thead>

            <?php
            foreach ($creditMemoLines as $creditMemoLine) {
                $itemNo = '';
                if ((int)$creditMemoLine["Type"] > 0) {
                    $itemNo = $creditMemoLine["No."];
                }

                if ($creditMemoLine["Type"] < 1) {
                    echo '<tbody>
                            <tr id="order-item-row-1">
                                <td class="col name" data-th="Product Name">
                                    <strong class="product name product-item-name">' . $creditMemoLine["Description"] . '</strong>
                                </td>
                                <td class="col sku" data-th="SKU"></td>
                                <td class="col price" data-th="Price">
                                </td>
                                <td class="col qty" data-th="Qty">
                                </td>
                                <td class="col subtotal" data-th="Subtotal">
                                </td>
                            </tr>
                        </tbody>';
                } else {
                    echo '<tbody>
                            <tr id="order-item-row-1">
                                <td class="col name" data-th="Product Name">
                                    <strong class="product name product-item-name">' . $creditMemoLine["Description"] . '</strong>
                                </td>
                                <td class="col sku" data-th="SKU">' . $itemNo . '</td>
                                <td class="col price" data-th="Price">
                                    <span class="price-excluding-tax" data-label="Excl. Tax">
                                        <span class="cart-price">
                                            <span class="price">' . $creditMemo["Currency Code"] . ' ' . number_format((float)$creditMemoLine["Amount"], 2, ',', '.') . '</span>
                                        </span>
                                    </span>
                                </td>
                                <td class="col qty" data-th="Qty">
                                    <ul class="items-qty">
                                        <li class="item">
                                            <span class="content">' . $creditMemoLine["Quantity"] . '</span>
                                        </li>
                                    </ul>
                                </td>
                                <td class="col subtotal" data-th="Subtotal">
                                    <span class="price-excluding-tax" data-label="Excl. Tax">
                                        <span class="cart-price">
                                            <span class="price">' . $creditMemo["Currency Code"] . ' ' . number_format((float)$creditMemoLine["Line Amount"], 2, ',', '.') . '</span>
                                        </span>
                                    </span>
                                </td>
                            </tr>
                        </tbody>';
                }
            }
            ?>

            <tfoot>
            <tr class="subtotal">
                <th colspan="4" class="mark" scope="row">
                    <?php echo __('Subtotal') ?>
                </th>
                <td class="amount" data-th="Subtotal">
                    <span class="price"><?php echo $creditMemo["Currency Code"]; ?> <?php echo number_format((float)$creditMemo["Amount"], 2, ',', '.') ?></span>
                </td>
            </tr>
            <tr class="shipping">
                <th colspan="4" class="mark" scope="row">
                    <?php echo __('VAT') ?>
                </th>
                <td class="amount" data-th="VAT &amp; VAT">
                    <span class="price"><?php echo $creditMemo["Currency Code"]; ?> <?php echo number_format((float)$creditMemo["Amount Including VAT"] - (float)$creditMemo["Amount"], 2, ',', '.') ?></span>
                </td>
            </tr>
            <tr class="grand_total">
                <th colspan="4" class="mark" scope="row">
                    <strong><?php echo __('Grand Total') ?></strong>
                </th>
                <td class="amount" data-th="Grand Total">
                    <strong><span class="price"><?php echo $creditMemo["Currency Code"]; ?> <?php echo number_format((float)$creditMemo["Amount Including VAT"], 2, ',', '.') ?></span></strong>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>


    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="/creditmemos/creditmemolist/">
                <span><?php echo __('Back to My Credit Memos') ?></span>
            </a>
        </div>
    </div>
</div>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?php echo __('Credit Memo Information') ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-order-shipping-address">
            <strong class="box-title"><span><?php echo __('Shipping Address') ?></span></strong>
            <div class="box-content">
                <address><?php echo $creditMemo["Ship-to Name"]; ?><br/>
                    <?php echo $creditMemo["Ship-to Address"]; ?><br />
                    <?php echo $creditMemo["Ship-to City"]; ?>,  <?php echo $creditMemo["Ship-to Post Code"]; ?><br/>
                    <?php echo $creditMemo["Ship-to Country/Region Code"]; ?><br/>
                </address>
            </div>
        </div>
        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span><?php echo __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
                <div><?php echo $creditMemo["Shipment Method Code"]; ?></div>
            </div>
        </div>
        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?php echo __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?php echo $creditMemo["Bill-to Name"]; ?><br/>
                    <?php echo $creditMemo["Bill-to Address"]; ?><br />
                    <?php echo $creditMemo["Bill-to City"]; ?>,  <?php echo $creditMemo["Bill-to Post Code"]; ?><br/>
                    <?php echo $creditMemo["Bill-to Country/Region Code"]; ?><br/>
                </address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?php echo __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <dl class="payment-method checkmemo">
                    <?php echo $creditMemo["Payment Method Code"]; ?>
                </dl>
            </div>
        </div>
    </div>
</div>

<!--

Below is a list of all sales credit memo header fields

[SelltoCustomerNo]
[No]
[BilltoCustomerNo]
[BilltoName]
[BilltoName2]
[BilltoAddress]
[BilltoAddress2]
[BilltoCity]
[BilltoContact]
[YourReference]
[ShiptoCode]
[ShiptoName]
[ShiptoName2]
[ShiptoAddress]
[ShiptoAddress2]
[ShiptoCity]
[ShiptoContact]
[PostingDate]
[ShipmentDate]
[PostingDescription]
[PaymentTermsCode]
[DueDate]
[PaymentDiscountPercentage]
[PmtDiscountDate]
[ShipmentMethodCode]
[LocationCode]
[ShortcutDimension1Code]
[ShortcutDimension2Code]
[CustomerPostingGroup]
[CurrencyCode]
[CurrencyFactor]
[CustomerPriceGroup]
[PricesIncludingVAT]
[InvoiceDiscCode]
[CustomerDiscGroup]
[LanguageCode]
[SalespersonCode]
[OnHold]
[Amount]
[AmountIncludingVAT]
[VATRegistrationNo]
[ReasonCode]
[GenBusPostingGroup]
[TransactionType]
[TransportMethod]
[VATCountryRegionCode]
[SelltoCustomerName]
[SelltoCustomerName2]
[SelltoAddress]
[SelltoAddress2]
[SelltoCity]
[SelltoContact]
[BilltoPostCode]
[BilltoCounty]
[BilltoCountryRegionCode]
[SelltoPostCode]
[SelltoCounty]
[SelltoCountryRegionCode]
[ShiptoPostCode]
[ShiptoCounty]
[ShiptoCountryRegionCode]
[Correction]
[DocumentDate]
[ExternalDocumentNo]
[PaymentMethodCode]
[TaxAreaCode]
[TaxLiable]
[VATBusPostingGroup]
[VATBaseDiscountPercentage]
[PrepaymentCreditMemo]
[PrepaymentOrderNo]
[Canceled]
[Paid]
[RemainingAmount]
[CustLedgerEntryNo]
[InvoiceDiscountAmount]
[CampaignNo]
[SelltoContactNo]
[BilltoContactNo]
[ResponsibilityCenter]
[ReturnOrderNo]
[AllowLineDisc]
[NoOfLines]
[PdfFileName]
[PdfUrl]

-->

<!--

Below is a list of all sales credit memo line fields

[SelltoCustomerNo]
[DocumentNo]
[LineNo]
[Type]
[No]
[NoIntegrationId]
[LocationCode]
[PostingGroup]
[ShipmentDate]
[Description]
[Description2]
[UnitofMeasure]
[Quantity]
[UnitPrice]
[UnitCostLCY]
[VATPercentage]
[LineDiscountPercentage]
[LineDiscountAmount]
[Amount]
[AmountIncludingVAT]
[AllowInvoiceDisc]
[GrossWeight]
[NetWeight]
[ShortcutDimension1Code]
[ShortcutDimension2Code]
[CustomerPriceGroup]
[BilltoCustomerNo]
[InvDiscountAmount]
[GenBusPostingGroup]
[GenProdPostingGroup]
[TransactionType]
[TransportMethod]
[VATBusPostingGroup]
[VATProdPostingGroup]
[VATBaseAmount]
[UnitCost]
[LineAmount]
[VATDifference]
[VATIdentifier]
[PrepaymentLine]
[PostingDate]
[VariantCode]
[BinCode]
[QtyperUnitofMeasure]
[UnitofMeasureCode]
[QuantityBase]
[ResponsibilityCenter]
[ItemCategoryCode]
[Nonstock]
[ProductGroupCode]
[ReturnReceiptNo]
[ReturnReceiptLineNo]
[ReturnReasonCode]
[AllowLineDisc]
[CustomerDiscGroup]

-->
