<?php
/** @var \Commerce365\CreditMemos\Block\CreditMemoDetails $block */
$creditMemo = $block->getCreditMemo();
$creditMemoLines = $block->safeGet($creditMemo, "Lines", []);

$remainingAmount = (float) $block->safeGet($creditMemo, "Remaining Amount", 0);
$status = 'Credited';
if ($remainingAmount > 0) {
    $status = 'Open (remaining: &euro; ' . number_format($remainingAmount, 2, ',', '.') . ')';
}
?>

<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper" >Credit Memo # <?= $block->safeGet($creditMemo, "No.") ?> </span>
    </h1>
    <span class="order-status"><?= $status ?></span>
    <div class="order-date">
        <span class="label"><?= __('Credit Memo Date:') ?></span> <date><?= date_format(date_create($block->safeGet($creditMemo, "Document Date")), "d-m-Y") ?></date>
    </div>
</div>

<div class="actions-toolbar order-actions-toolbar">
    <div class="actions">
        <a href="<?= $block->safeGet($creditMemo, "PDFUrl") ?>" class="action order" target="_blank">
            <span><?= __('Download PDF') ?></span>
        </a>
    </div>
</div>

<ul class="items order-links"><li class="nav item current"><strong><?= __('Items Credited') ?></strong></li></ul><div class="order-details-items ordered">

    <div class="order-title">
        <strong><?= __('Items Credited') ?></strong>
    </div>

    <div class="table-wrapper order-items">
        <table class="data table table-order-items" id="my-orders-table">
            <caption class="table-caption"><?= __('Items Credited') ?></caption>
            <thead>
            <tr>
                <th class="col name"><?= __('Product Name') ?></th>
                <th class="col sku"><?= __('SKU') ?></th>
                <th class="col price"><?= __('Price') ?></th>
                <th class="col qty"><?= __('Qty') ?></th>
                <th class="col subtotal"><?= __('Subtotal') ?></th>
            </tr>
            </thead>

            <?php foreach ($creditMemoLines as $creditMemoLine): ?>
                <?php
                $type = (int)$block->safeGet($creditMemoLine, "Type");
                $itemNo = $type > 0 ? $block->safeGet($creditMemoLine, "No.") : '';
                ?>
                <tbody>
                <tr id="order-item-row-1">
                    <td class="col name" data-th="Product Name">
                        <strong class="product name product-item-name"><?= $block->safeGet($creditMemoLine, "Description") ?></strong>
                    </td>
                    <td class="col sku" data-th="SKU"><?= $type > 0 ? $itemNo : '' ?></td>
                    <td class="col price" data-th="Price">
                        <?php if ($type > 0): ?>
                            <span class="price-excluding-tax" data-label="Excl. Tax">
                                    <span class="cart-price">
                                        <span class="price">
                                            <?= $block->safeGet($creditMemo, "Currency Code") ?> <?= number_format((float)$block->safeGet($creditMemoLine, "Amount"), 2, ',', '.') ?>
                                        </span>
                                    </span>
                                </span>
                        <?php endif; ?>
                    </td>
                    <td class="col qty" data-th="Qty">
                        <ul class="items-qty">
                            <li class="item">
                                <span class="content"><?= $block->safeGet($creditMemoLine, "Quantity") ?></span>
                            </li>
                        </ul>
                    </td>
                    <td class="col subtotal" data-th="Subtotal">
                        <?php if ($type > 0): ?>
                            <span class="price-excluding-tax" data-label="Excl. Tax">
                                    <span class="cart-price">
                                        <span class="price">
                                            <?= $block->safeGet($creditMemo, "Currency Code") ?> <?= number_format((float)$block->safeGet($creditMemoLine, "Line Amount"), 2, ',', '.') ?>
                                        </span>
                                    </span>
                                </span>
                        <?php endif; ?>
                    </td>
                </tr>
                </tbody>
            <?php endforeach; ?>

            <tfoot>
            <tr class="subtotal">
                <th colspan="4" class="mark" scope="row">
                    <?= __('Subtotal') ?>
                </th>
                <td class="amount" data-th="Subtotal">
                    <span class="price"><?= $block->safeGet($creditMemo, "Currency Code") ?> <?= number_format((float)$block->safeGet($creditMemo, "Amount"), 2, ',', '.') ?></span>
                </td>
            </tr>
            <tr class="shipping">
                <th colspan="4" class="mark" scope="row">
                    <?= __('VAT') ?>
                </th>
                <td class="amount" data-th="VAT &amp; VAT">
                    <span class="price"><?= $block->safeGet($creditMemo, "Currency Code") ?> <?= number_format((float)$block->safeGet($creditMemo, "Amount Including VAT") - (float)$block->safeGet($creditMemo, "Amount"), 2, ',', '.') ?></span>
                </td>
            </tr>
            <tr class="grand_total">
                <th colspan="4" class="mark" scope="row">
                    <strong><?= __('Grand Total') ?></strong>
                </th>
                <td class="amount" data-th="Grand Total">
                    <strong><span class="price"><?= $block->safeGet($creditMemo, "Currency Code") ?> <?= number_format((float)$block->safeGet($creditMemo, "Amount Including VAT"), 2, ',', '.') ?></span></strong>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="/creditmemos/creditmemolist/">
                <span><?= __('Back to My Credit Memos') ?></span>
            </a>
        </div>
    </div>
</div>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= __('Credit Memo Information') ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-order-shipping-address">
            <strong class="box-title"><span><?= __('Shipping Address') ?></span></strong>
            <div class="box-content">
                <address><?= $block->safeGet($creditMemo, "Ship-to Name") ?><br/>
                    <?= $block->safeGet($creditMemo, "Ship-to Address") ?><br />
                    <?= $block->safeGet($creditMemo, "Ship-to City") ?>,  <?= $block->safeGet($creditMemo, "Ship-to Post Code") ?><br/>
                    <?= $block->safeGet($creditMemo, "Ship-to Country/Region Code") ?><br/>
                </address>
            </div>
        </div>
        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span><?= __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
                <div><?= $block->safeGet($creditMemo, "Shipment Method Code") ?></div>
            </div>
        </div>
        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?= $block->safeGet($creditMemo, "Bill-to Name") ?><br/>
                    <?= $block->safeGet($creditMemo, "Bill-to Address") ?><br />
                    <?= $block->safeGet($creditMemo, "Bill-to City") ?>,  <?= $block->safeGet($creditMemo, "Bill-to Post Code") ?><br/>
                    <?= $block->safeGet($creditMemo, "Bill-to Country/Region Code") ?><br/>
                </address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <dl class="payment-method checkmemo">
                    <?= $block->safeGet($creditMemo, "Payment Method Code") ?>
                </dl>
            </div>
        </div>
    </div>
</div>
