<?php
/** @var \Commerce365\CreditMemos\Block\CreditMemoList  $block */
$totalResults = 0;
$creditMemos = [];

$creditMemosResponse = $this->getCreditMemos();
if (!empty($creditMemosResponse)) {
    $creditMemos = $creditMemosResponse["salesDocuments"];
    $totalResults = $creditMemosResponse["totalResults"];
}
?>

<div class="table-wrapper orders-history">
<?php if (count($creditMemos) > 0): ?>
    <form action="<?= $this->getFilterActionUrl() ?>" method="get">
        <div class="search-form-fields">
            <input type="text" placeholder="<?= __('Search...') ?>" name="searchString"/>
            <button type="submit" title="<?= __('Search') ?>" class="action primary">
                <span><?= __('Search') ?></span>
            </button>
        </div>
    </form>
    <?php if ($this->getSearchString()): ?>
        <?= __('Current filter')?>: <?= $this->getSearchString()?>
        <a href="<?= $this->getFilterActionUrl()?>"><?= __('Reset') ?></a>
    <?php endif; ?>
    <table class="data table table-order-items history" id="my-orders-table">
        <thead>
        <tr>
            <?php if($this->isColumnExists($creditMemos, 'No.')): ?>
                <th scope="col" class="col id">
                    <a href="<?= $this->getSortLink('No.')?>">
                        <?= __('Credit Memo #') ?>
                        <?= $this->getSortIcon('No.') ?>
                    </a>
                </th>
            <?php endif; ?>
            <?php if($this->isColumnExists($creditMemos, 'Document Date')): ?>
                <th scope="col" class="col date">
                    <a href="<?= $this->getSortLink('Document Date')?>">
                        <?= __('Date') ?>
                        <?= $this->getSortIcon('Document Date') ?>
                    </a>
                </th>
            <?php endif; ?>
            <?php if($this->isColumnExists($creditMemos, 'Sell-to Customer Name')): ?>
                <th scope="col" class="col shipping">
                    <a href="<?= $this->getSortLink('Sell-to Customer Name')?>">
                        <?= __('Credit To') ?>
                        <?= $this->getSortIcon('Sell-to Customer Name') ?>
                    </a>
                </th>
            <?php endif; ?>
            <?php if($this->isColumnExists($creditMemos, 'Amount Including VAT')): ?>
                <th scope="col" class="col total">
                    <a href="<?= $this->getSortLink('Amount Including VAT')?>">
                        <?= __('Credit Total') ?>
                        <?= $this->getSortIcon('Amount Including VAT') ?>
                    </a>
                </th>
            <?php endif; ?>
            <?php if($this->isColumnExists($creditMemos, 'Remaining Amount')): ?>
                <th scope="col" class="col total">
                    <a href="<?= $this->getSortLink('Remaining Amount')?>">
                        <?= __('Open Amount') ?>
                        <?= $this->getSortIcon('Remaining Amount') ?>
                    </a>
                </th>
            <?php endif; ?>
            <th scope="col" class="col actions">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($creditMemos as $creditMemo): ?>
            <tr>
                <?php if($this->isColumnExists($creditMemos, 'No.')): ?>
                    <td data-th="Order #" class="col id"><?= $creditMemo["No."] ?></td>
                <?php endif; ?>
                <?php if($this->isColumnExists($creditMemos, 'Document Date')): ?>
                    <td data-th="Date" class="col date"><?= date_format(date_create($creditMemo["Document Date"]), "d-m-Y") ?></td>
                <?php endif; ?>
                <?php if($this->isColumnExists($creditMemos, 'Sell-to Customer Name')): ?>
                    <td data-th="Ship To #" class="col id"><?= $creditMemo["Sell-to Customer Name"] ?></td>
                <?php endif; ?>
                <?php if($this->isColumnExists($creditMemos, 'Amount Including VAT')): ?>
                    <td data-th="Total" class="col total"><?= $creditMemo["Currency Code"] ?> <?= number_format((float)$creditMemo["Amount Including VAT"], 2, ',', '.') ?></td>
                <?php endif; ?>
                <?php if($this->isColumnExists($creditMemos, 'Remaining Amount')): ?>
                    <td data-th="Total" class="col total"><?= $creditMemo["Currency Code"] ?> <?= number_format((float)$creditMemo["Remaining Amount"], 2, ',', '.') ?></td>
                <?php endif; ?>
                <td data-th="Actions" class="col actions">
                    <a href="<?= $this->getViewUrl($creditMemo["id"]) ?>" class="action view">
                        <span><?= __("View Credit Memo") ?></span>
                    </a>
                    <a href="<?= $creditMemo["PDFUrl"] ?>" class="action order" target="_blank">
                        <span>PDF</span>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="message info empty"><span><?= __('No credit memos found.') ?></span></div>
<?php endif; ?>
</div>

<?php if ($totalResults > $block->getPageSize()): ?>
    <div>
        <?= __('Page:') ?> <?= $block->getPage() ?> <?= __('of') ?> <?= $creditMemosResponse["totalPages"] ?>
    </div>
    <div>
        <?php if ($block->getPage() > 1): ?>
        <a href="<?= $block->getPreviousPageUrl() ?>" class="action order"><?= __('Previous') ?></a>
        <?php endif; ?>
        <?php if ($block->getPage() > 1 && $block->getPage() < $creditMemosResponse["totalPages"]): ?>
            -
        <?php endif; ?>
        <?php if ($block->getPage() < $creditMemosResponse["totalPages"]): ?>
        <a href="<?= $block->getNextPageUrl() ?>" class="action order"><?= __('Next') ?></a>
        <?php endif; ?>
    </div>
<?php endif; ?>
