<?php declare(strict_types=1);

use Commerce365\CreditMemos\Block\CreditMemoDetails;
use Magento\Framework\Escaper;

/** @var CreditMemoDetails $block */
/** @var Escaper $escaper */

$creditMemo = $block->getCreditMemo();
$creditMemoLines = $creditMemo["Lines"];
$status = 'Credited';

if ((float)$creditMemo["Remaining Amount"] > 0) {
    // TODO: show currency based on getCurrency
    $status = 'Open (remaining: € ' . number_format((float)$creditMemo["Remaining Amount"], 2, ',', '.') . ')';
}
?>

<div class="md:flex md:justify-between items-center mb-3">
    <div class="lg:flex items-center text-center md:text-left">
        <div class="lg:inline-block">
            <h2 class="text-2xl">
                <span><?= $escaper->escapeHtml(__('Credit Memo # %1', $creditMemo["No."])) ?></span>
            </h2>
            <div class="order-date">
                <span><?= $escaper->escapeHtml(__('Credit Memo Date:')) ?></span>
                <date><?= date_format(date_create($creditMemo["Document Date"]), "d-m-Y") ?></date>
            </div>
        </div>
        <div class="mt-3 md:mt-0 lg:inline-block lg:ml-5">
            <span
                class="order-status inline-block px-3 py-3 border rounded border-container"><?= $escaper->escapeHtml($status) ?></span>
        </div>
    </div>
    <a href="<?= $escaper-> escapeUrl($creditMemo["PDFUrl"]) ?>" class="btn btn-secondary order" target="_blank"
        rel="noopener noreferrer">
        <span><?= $escaper->escapeHtml(__('Download PDF')) ?></span>
    </a>
</div>

<div class="order-details-items ordered">
    <div class="-mx-4">
        <ul class="items order-links">
            <li class="nav item current"><strong><?= $escaper->escapeHtml(__('Items Credited')) ?></strong></li>
        </ul>
    </div>
    <div class="p4 card">
        <div class="table-wrapper order-items overflow-auto">
            <table id="my-orders-table" class="w-full">
                <caption class="order-title sr-only"><?= __('Items Credited') ?></caption>
                <thead>
                    <tr>
                        <th class="col name p-2 text-left"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                        <th class="col sku p-2 text-left"><?= $escaper->escapeHtml(__('SKU')) ?></th>
                        <th class="col price p-2 text-left"><?= $escaper->escapeHtml(__('Price')) ?></th>
                        <th class="col qty p-2 text-left"><?= $escaper->escapeHtml(__('Qty')) ?></th>
                        <th class="col subtotal p-2 text-left"><?= $escaper->escapeHtml(__('Subtotal')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($creditMemoLines as $creditMemoLine): ?>
                    <?php
                            $itemNo = '';
                            if ((int)$creditMemoLine["Type"] > 0) {
                                $itemNo = $creditMemoLine["No."];
                            }
                        ?>
                    <?php if ($creditMemoLine["Type"] < 1): ?>
                    <tr class="even:bg-gray-100 align-top">
                        <td class="col name p-2" data-th="Product Name">
                            <strong class="product name product-item-name">
                                <?= $creditMemoLine["Description"]; ?>
                            </strong>
                        </td>
                        <td class="col sku p-2"></td>
                        <td class="col price p-2"></td>
                        <td class="col qty p-2"></td>
                        <td class="col subtotal p-2"></td>
                    </tr>
                    <?php else: ?>
                    <tr class="even:bg-gray-100 align-top">
                        <td class="col name p-2">
                            <strong class="product name product-item-name">
                                <?= $creditMemoLine["Description"]; ?>
                            </strong>
                        </td>
                        <td class="col sku p-2"><?= $itemNo; ?></td>
                        <td class="col price p-2">
                            <span class="price-excluding-tax" data-label="Excl. Tax">
                                <span class="cart-price">
                                    <span
                                        class="price"><?= $creditMemo["Currency Code"] . ' ' . number_format((float)$creditMemoLine["Amount"], 2, ',', '.'); ?></span>
                                </span>
                            </span>
                        </td>
                        <td class="col qty p-2">
                            <ul class="items-qty">
                                <li class="item">
                                    <span class="content"><?= $creditMemoLine["Quantity"]; ?></span>
                                </li>
                            </ul>
                        </td>
                        <td class="col subtotal p-2">
                            <span class="price-excluding-tax" data-label="Excl. Tax">
                                <span class="cart-price">
                                    <span
                                        class="price"><?= $creditMemo["Currency Code"] . ' ' . number_format((float)$creditMemoLine["Line Amount"], 2, ',', '.'); ?></span>
                                </span>
                            </span>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <?php endforeach; ?>
                </tbody>

                <tfoot>
                    <tr class="subtotal">
                        <th colspan="4" class="p-2 text-right" scope="row"><?= __('Subtotal') ?></th>
                        <td class="amount p-2">
                            <span class="price"><?= $creditMemo["Currency Code"]; ?>
                                <?= number_format((float)$creditMemo["Amount"], 2, ',', '.') ?></span>
                        </td>
                    </tr>
                    <tr class="shipping">
                        <th colspan="4" class="p-2 text-right" scope="row">
                            <?= $escaper->escapeHtml(__('VAT')) ?>
                        </th>
                        <td class="amount p-2">
                            <span class="price"><?= $creditMemo["Currency Code"]; ?>
                                <?= number_format((float)$creditMemo["Amount Including VAT"] - (float)$creditMemo["Amount"], 2, ',', '.') ?></span>
                        </td>
                    </tr>
                    <tr class="grand_total">
                        <th colspan="4" class="p-2 text-right" scope="row">
                            <strong><?= $escaper->escapeHtml(__('Grand Total')) ?></strong>
                        </th>
                        <td class="amount p-2">
                            <strong><span class="price"><?= $creditMemo["Currency Code"]; ?>
                                    <?= number_format((float)$creditMemo["Amount Including VAT"], 2, ',', '.') ?></span></strong>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="actions-toolbar">
            <div class="secondary">
                <?php  // Todo: add getbackUrl ?>
                <a class="action back" href="/creditmemos/creditmemolist/">
                    <span><?= $escaper->escapeHtml(__('Back to My Credit Memos')) ?></span>
                </a>
            </div>
        </div>
    </div>
    <div class="mt-8">
        <div class="block-title mb-2">
            <strong><?= $escaper->escapeHtml(__('Credit Memo Information')) ?></strong>
        </div>
        <div class="p-4 card">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="order-shipping-address">
                    <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Shipping Address')) ?></strong>
                    <address class="not-italic">
                        <?= $creditMemo["Ship-to Name"]; ?><br />
                        <?= $creditMemo["Ship-to Address"]; ?><br />
                        <?= $creditMemo["Ship-to City"]; ?>, <?= $creditMemo["Ship-to Post Code"]; ?><br />
                        <?= $creditMemo["Ship-to Country/Region Code"]; ?><br />
                    </address>
                </div>
                <div class="order-shipping-method">
                    <strong class="block text-lg mb-2"><?= __('Shipping Method') ?></strong>
                    <div><?= $creditMemo["Shipment Method Code"]; ?></div>
                </div>
                <div class="order-billing-address">
                    <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Billing Address')) ?></strong>
                    <address class="not-italic">
                        <?= $creditMemo["Bill-to Name"]; ?><br />
                        <?= $creditMemo["Bill-to Address"]; ?><br />
                        <?= $creditMemo["Bill-to City"]; ?>, <?= $creditMemo["Bill-to Post Code"]; ?><br />
                        <?= $creditMemo["Bill-to Country/Region Code"]; ?><br />
                    </address>
                </div>
                <div class="order-billing-method">
                    <strong class="block text-lg mb-2"><?= $escaper->escapeHtml(__('Payment Method')) ?></strong>
                    <dl class="payment-method checkmemo">
                        <?= $creditMemo["Payment Method Code"]; ?>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>